// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/proto/metrics/metrics.proto

package metrics_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric_MType int32

const (
	Metric_MTYPE_UNDEFINED Metric_MType = 0
	Metric_MTYPE_COUNTER   Metric_MType = 1
	Metric_MTYPE_GAUGE     Metric_MType = 2
)

// Enum value maps for Metric_MType.
var (
	Metric_MType_name = map[int32]string{
		0: "MTYPE_UNDEFINED",
		1: "MTYPE_COUNTER",
		2: "MTYPE_GAUGE",
	}
	Metric_MType_value = map[string]int32{
		"MTYPE_UNDEFINED": 0,
		"MTYPE_COUNTER":   1,
		"MTYPE_GAUGE":     2,
	}
)

func (x Metric_MType) Enum() *Metric_MType {
	p := new(Metric_MType)
	*p = x
	return p
}

func (x Metric_MType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric_MType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_metrics_metrics_proto_enumTypes[0].Descriptor()
}

func (Metric_MType) Type() protoreflect.EnumType {
	return &file_pkg_proto_metrics_metrics_proto_enumTypes[0]
}

func (x Metric_MType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric_MType.Descriptor instead.
func (Metric_MType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_metrics_metrics_proto_rawDescGZIP(), []int{1, 0}
}

type UpdateMetricsBulkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsBulkRequest) Reset() {
	*x = UpdateMetricsBulkRequest{}
	mi := &file_pkg_proto_metrics_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsBulkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsBulkRequest) ProtoMessage() {}

func (x *UpdateMetricsBulkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_metrics_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsBulkRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricsBulkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_metrics_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMetricsBulkRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type  Metric_MType           `protobuf:"varint,2,opt,name=type,proto3,enum=metrics.Metric_MType" json:"type,omitempty"`
	// Types that are valid to be assigned to MValue:
	//
	//	*Metric_Delta
	//	*Metric_Value
	MValue        isMetric_MValue `protobuf_oneof:"m_value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_pkg_proto_metrics_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_metrics_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_pkg_proto_metrics_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *Metric) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Metric) GetType() Metric_MType {
	if x != nil {
		return x.Type
	}
	return Metric_MTYPE_UNDEFINED
}

func (x *Metric) GetMValue() isMetric_MValue {
	if x != nil {
		return x.MValue
	}
	return nil
}

func (x *Metric) GetDelta() int64 {
	if x != nil {
		if x, ok := x.MValue.(*Metric_Delta); ok {
			return x.Delta
		}
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		if x, ok := x.MValue.(*Metric_Value); ok {
			return x.Value
		}
	}
	return 0
}

type isMetric_MValue interface {
	isMetric_MValue()
}

type Metric_Delta struct {
	Delta int64 `protobuf:"varint,3,opt,name=delta,proto3,oneof"`
}

type Metric_Value struct {
	Value float64 `protobuf:"fixed64,4,opt,name=value,proto3,oneof"`
}

func (*Metric_Delta) isMetric_MValue() {}

func (*Metric_Value) isMetric_MValue() {}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_pkg_proto_metrics_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_metrics_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_pkg_proto_metrics_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_pkg_proto_metrics_metrics_proto protoreflect.FileDescriptor

const file_pkg_proto_metrics_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/metrics/metrics.proto\x12\ametrics\"E\n" +
	"\x18UpdateMetricsBulkRequest\x12)\n" +
	"\ametrics\x18\x01 \x03(\v2\x0f.metrics.MetricR\ametrics\"\xc2\x01\n" +
	"\x06Metric\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.metrics.Metric.MTypeR\x04type\x12\x16\n" +
	"\x05delta\x18\x03 \x01(\x03H\x00R\x05delta\x12\x16\n" +
	"\x05value\x18\x04 \x01(\x01H\x00R\x05value\"@\n" +
	"\x05MType\x12\x13\n" +
	"\x0fMTYPE_UNDEFINED\x10\x00\x12\x11\n" +
	"\rMTYPE_COUNTER\x10\x01\x12\x0f\n" +
	"\vMTYPE_GAUGE\x10\x02B\t\n" +
	"\am_value\"F\n" +
	"\x03Ack\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2O\n" +
	"\aMetrics\x12D\n" +
	"\x11UpdateMetricsBulk\x12!.metrics.UpdateMetricsBulkRequest\x1a\f.metrics.AckB\x0fZ\rmetrics.protob\x06proto3"

var (
	file_pkg_proto_metrics_metrics_proto_rawDescOnce sync.Once
	file_pkg_proto_metrics_metrics_proto_rawDescData []byte
)

func file_pkg_proto_metrics_metrics_proto_rawDescGZIP() []byte {
	file_pkg_proto_metrics_metrics_proto_rawDescOnce.Do(func() {
		file_pkg_proto_metrics_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_metrics_metrics_proto_rawDesc), len(file_pkg_proto_metrics_metrics_proto_rawDesc)))
	})
	return file_pkg_proto_metrics_metrics_proto_rawDescData
}

var file_pkg_proto_metrics_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_metrics_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_metrics_metrics_proto_goTypes = []any{
	(Metric_MType)(0),                // 0: metrics.Metric.MType
	(*UpdateMetricsBulkRequest)(nil), // 1: metrics.UpdateMetricsBulkRequest
	(*Metric)(nil),                   // 2: metrics.Metric
	(*Ack)(nil),                      // 3: metrics.Ack
}
var file_pkg_proto_metrics_metrics_proto_depIdxs = []int32{
	2, // 0: metrics.UpdateMetricsBulkRequest.metrics:type_name -> metrics.Metric
	0, // 1: metrics.Metric.type:type_name -> metrics.Metric.MType
	1, // 2: metrics.Metrics.UpdateMetricsBulk:input_type -> metrics.UpdateMetricsBulkRequest
	3, // 3: metrics.Metrics.UpdateMetricsBulk:output_type -> metrics.Ack
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_metrics_metrics_proto_init() }
func file_pkg_proto_metrics_metrics_proto_init() {
	if File_pkg_proto_metrics_metrics_proto != nil {
		return
	}
	file_pkg_proto_metrics_metrics_proto_msgTypes[1].OneofWrappers = []any{
		(*Metric_Delta)(nil),
		(*Metric_Value)(nil),
	}
	file_pkg_proto_metrics_metrics_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_metrics_metrics_proto_rawDesc), len(file_pkg_proto_metrics_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_metrics_metrics_proto_goTypes,
		DependencyIndexes: file_pkg_proto_metrics_metrics_proto_depIdxs,
		EnumInfos:         file_pkg_proto_metrics_metrics_proto_enumTypes,
		MessageInfos:      file_pkg_proto_metrics_metrics_proto_msgTypes,
	}.Build()
	File_pkg_proto_metrics_metrics_proto = out.File
	file_pkg_proto_metrics_metrics_proto_goTypes = nil
	file_pkg_proto_metrics_metrics_proto_depIdxs = nil
}
