name: static-analysis
on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  staticlint:
    name: Run Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install staticlint
        run: go install ./cmd/staticlint
      - name: Run staticlint
        run: staticlint ./...
